Fix Mapreduce startup (based on pull request #36)
$GOBBLIN_HOME/build.gradle:
- bump avro version to 1.7.6 to conform with the version of avro-mapred
- force guava version 15.0: otherwise during the build gradle may pick up guava 17.0 and will include it in the /lib directory
  instead of the defined version 15.0. (This may lead to issues like
  IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat)

$GOBBLIN_HOME/conf/gobblin-env.sh:
- A script to initialize environment variables called by gobblin-standalone.sh and gobblin-mapreduce.sh

$GOBBLIN_HOME/bin/gobblin-mapreduce.sh:
- Job configuration as command line parameter
- JobTracker/ResourceManager and FileSystem arguments became optional
- Accepts multiple job jars as command line arguments
- $GOBBLIN_WORK_DIR can be overridden by the --workdir parameter

$GOBBLIN_HOME/bin/gobblin-standalone.sh:
- Job configuration as command line parameter
- Accepts multiple job jars as command line arguments
- $GOBBLIN_WORK_DIR can be overridden by the --workdir parameter

$GOBBLIN_HOME/gobblin-runtime/src/main/java/gobblin/runtime/mapreduce/CliMRJobLauncher.java :
- Use GenericOptionsParser to be able to pick up Gobblin as well as Hadoop related command line arguments

Others:
- Removed internal Linkedin dependencies from LIBJARS
- Missing command line toggles (sysconfig and jobconfig)added
- Load Gobblin related dependencies first to HADOOP_CLASSPATH to avoid jar hell